version: "2"

networks:
  app-network:
    driver: bridge

services:
  redis:
    image: "redis:alpine"
    container_name: "bot_redis"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
    ports:
      - 6379:6379
